@startuml
'https://plantuml.com/state-diagram

scale 300 width
hide empty description

state "Init" as Init
state "Idle" as Idle
state "Find closest\nnode Id to target" as FindClosestNodeIdToTarget
state "Find closest\nnode Id to bot" as FindClosestNodeIdToBot

'Idle
[*] -down-> Init : Bot created
Init : Init bot when just created
Init : or reset pathfinding
Init -left-> Idle : Pathfinding is reset

'Targeting
Idle -left-> FindClosestNodeIdToTarget : [BotTargetPlayer != -1] or\n[BotTargetPosition != -1]
FindClosestNodeIdToTarget --> FindClosestNodeIdToBot : [BotClosestNodeIdToTarget = -1]
FindClosestNodeIdToBot --> FindNextNodeId : [BotClosestNodeIdToBot != -1]

state "Find next\nposition in path" as FindNextNodeId {
    state BeginPathFindingChoice <<choice>>
    state BotFolowPathChoice <<choice>>
    [*] --> BotFolowPathChoice
    state BotPrevNodeIdChoice <<choice>>
    state BotNextNodeIsTargetChoice <<choice>>
    state "Move to closest\nnode position to bot" as MoveToClosestNodeToBot
    state "Move to next\nnode position in path" as MoveToNextNodeInPath
    state "Move to target\nposition" as MoveToTargetPosition
    state "Follow to\nnext position" as FollowToNextPosition
    state JoinClosestNode <<join>>
    state JoinNextNode <<join>>
    state Join2 <<join>>

    'Bot just begun follow path
    BotFolowPathChoice --> BeginPathFindingChoice : Next node\nis not target
    BeginPathFindingChoice --> JoinClosestNode : Bot just begun\nfollow path\n[BotPrevNodeId == -1]\n&&\nNext position is\nhigher than bot's position\n|| \nCan't see\nnext position
    BeginPathFindingChoice --> JoinNextNode : Else
    JoinClosestNode --> MoveToClosestNodeToBot

    BotFolowPathChoice -left-> BotNextNodeIsTargetChoice : Next node\n is a target\n&&\nCan see\ntarget position
    BotNextNodeIsTargetChoice --> MoveToTargetPosition : Target position is not\nhigher than bot's position
    BotNextNodeIsTargetChoice --> BotPrevNodeIdChoice : Target position is\nhigher than bot's position\n&&\nDistance to next position\n closer than to target position

    'End pathfinding
    BotPrevNodeIdChoice --> JoinNextNode : Bot already\nfollow path\n[BotPrevNodeId != -1]
    BotPrevNodeIdChoice --> JoinClosestNode : Bot just begun\nfollow path\n[BotPrevNodeId == -1]
    JoinNextNode --> MoveToNextNodeInPath
    MoveToClosestNodeToBot --> Join2
    MoveToNextNodeInPath --> Join2
    MoveToTargetPosition --> Join2
    Join2 --> FollowToNextPosition
    FollowToNextPosition --> [*]
}



@enduml
